name = "Create"
author = "jflocke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b37a35f4635f54755e0aeec72ba9b310f6f0416bf3a63ea28aaba4b38218f97f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
