name = "Create"
author = "jflocke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72996164826b3cf06447d420ac596548afc6f2a80c45c81d79c0f7e6791cd27f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
