name = "Create"
author = "jflocke"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02fee5ef518532f4929ca1ece3060115e4934acb7f4987eed597f00f1285088e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
